-- 코드를 입력하세요
SELECT F.FOOD_TYPE, REST_ID,REST_NAME,FAVORITES 
FROM REST_INFO F 
JOIN
(SELECT FOOD_TYPE, MAX(FAVORITES)AS MAXFAVORITES FROM REST_INFO 
GROUP BY FOOD_TYPE)AS M 
ON F.FOOD_TYPE=M.FOOD_TYPE AND F.FAVORITES=M.MAXFAVORITES
ORDER BY FOOD_TYPE DESC;

# SELECT * FROM REST_INFO;
